#!/bin/sh
echo "$(date):正在下载adblockplus规则..."
/usr/bin/wget -O- https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt | grep ^\|\|[^\*]*\^$ | sed -e 's:||:address\=\/:' -e 's:\^:/0\.0\.0\.0:' > /tmp/dnsmasq.adblock
diff /tmp/dnsmasq.adblock /etc/dnsmasq.d/dnsmasq.adblock >/dev/null
[ $? = 0 ] && echo "$(date):adblockplus本地规则和服务器规则相同，无需更新!" && exit
echo "$(date):检测到adblockplus规则有更新，开始转换规则！"
sed -i '/youku/d' /tmp/dnsmasq.adblock >/dev/null 2>&1
sed -i '/[1-9]\{1,3\}\.[1-9]\{1,3\}\.[1-9]\{1,3\}\.[1-9]\{1,3\}/d' /tmp/dnsmasq.adblock >/dev/null 2>&1
mv /tmp/dnsmasq.adblock /etc/dnsmasq.d/dnsmasq.adblock 
echo "$(date):adblockplus规则转换完成，应用新规则。"
/etc/init.d/dnsmasq restart
