#!/bin/sh
cat /etc/adblocklist/adblock | sed "s/,/\n/g" | sed "s/^/ipset=&\/./g" | sed "s/$/\/black_koolproxy/g"  >> /tmp/adblock.conf
mv /tmp/adblock.conf /usr/share/koolproxy/adblock.conf
rm -f /tmp/dnsmasq.d/adblock.conf
ln -s /usr/share/koolproxy/adblock.conf /tmp/dnsmasq.d/adblock.conf
ipset -F black_koolproxy
/etc/init.d/dnsmasq restart
